### ISSUE TITLE
H2O.ai benchmark is out of date

### ISSUE THREAD

**Issue by AdrianAntico** [IyarLin/R-advantages-over-python#14]
Great repo by the way!

The benchmark has quite different results now that Polars and DataFrames.jl have matured a bit more, even datatable for python. I've been working on automl packages for both R and Python (the R one is much further along and the Python one is relatively new) and I can't state enough how almost everything I do to create these packages is more easily done in R. 

Now that Python does have some promising data wrangling packages (polars / datatable) I think it's important to focus on the capabilities in those packages compared to data.table (which is still king in my book). The example you have with the case-when of dplyr vs pandas is a superb example of two things: the capabilities that exists and the ease of which to deploy them, and in both cases, R wins. I believe that you'll find this to be true to more you go digging into feature engineering capabilities from all those packages.

Anyway, great work

**Comment by IyarLin** [comment]
Part of the motivation for starting this repo was to encourage better packages in python. If python developers become more aware of their shortcomings it could help facilitate better package development. Polars sounds like good news - hope I get around to trying it out soon. Maybe after it gains some traction I'll expand the syntax comparison to Polars as well.
