### ISSUE TITLE
Numpy can work with different types

### ISSUE THREAD

**Issue by pisarik** [IyarLin/R-advantages-over-python#15]
I am referring to this part of your comparison:

https://github.com/IyarLin/R-advantages-over-python/blob/063366176e437e70029e864ba9c5a7ecec32ba5e/README.md?plain=1#L1316-L1318

It seems that you can easily do that:
```python
values = np.array(['a', 1, (1, 2, 3), 'wow', ['sweet', 2]])
indices = np.arange(len(values))
values[indices > 2]
```

    ## array(['wow', list(['sweet', 2])], dtype=object)

**Comment by IyarLin** [comment]
I stand corrected. Removed that portion of the comparison. Thanks!
