### ISSUE TITLE
Moving windows example

### ISSUE THREAD

**Issue by jl5000** [IyarLin/R-advantages-over-python#2]
I'm not so sure it's objectively worse in Python. It's about the same number of lines, and the only difference seems to be a subjective judgement call about the ubiquitousness of functions. I'm not sure it's a strong enough example.

**Comment by IyarLin** [comment]
Hi, let's use the dedicated discussion tab for that. I've started this discussion here:

https://github.com/IyarLin/R-advantages-over-python/discussions/4#discussion-3349001
